### ISSUE TITLE
如果有 EHCI / XHCI Hand-off 功能，建议仅在出现 USB 设备连接时启动停滞的情况下启用。

### ISSUE THREAD

**Issue by Z-fly** [huangyanan/Hackintosh-EFI-for-deskmini-310-dw1820#2]
https://oc.skk.moe/5-booter.html
不开XHCI Hand-off就是不行吗？

**Comment by huangyanan** [comment]
USB Configuration, XHCI Hand-off, Enabled （关键）

**Comment by Z-fly** [comment]
> USB Configuration, XHCI Hand-off, Enabled （关键）

不开就是卡在OC引导那是吗？

**Comment by huangyanan** [comment]
是的。
