### ISSUE TITLE
你的oc不用更改minDate吗

### ISSUE THREAD

**Issue by nabaonan** [huangyanan/Hackintosh-EFI-for-deskmini-310-dw1820#3]

**Comment by huangyanan** [comment]
没有配置到你描述的配置。

**Comment by nabaonan** [comment]
> 配置

我之前没有配置就不会出现引导系统的选项，我之前在oc0.7.2遇到的，这个选项在uefi里面配的，不知你的为啥是好的

**Comment by huangyanan** [comment]
不清楚，我是基于官方的默认配置改的，改动比较少。建议看https://blog.xjn819.com/post/opencore-guide.html

**Comment by nabaonan** [comment]
> 不清楚，我是基于官方的默认配置改的，改动比较少。建议看https://blog.xjn819.com/post/opencore-guide.html

![image](https://user-images.githubusercontent.com/17247526/135882470-164878c7-6e05-4393-a228-62abfd58f561.png)
官网catalina及以下确实要配置-1，xjn大佬的确实没有标识，不知是不是0.7.2版本，你的如果是0.7.2然后没有修改这个参数还能引导catalina感觉挺奇怪的，我的台式机和笔记本都没法出现系统选择菜单
