### ISSUE TITLE
请问你是从clover转到oc的吗？10.15可以直接升级到11/12吗（clover）

### ISSUE THREAD

**Issue by Jiyvn** [huangyanan/Hackintosh-EFI-for-deskmini-310-dw1820#5]
请问我应该怎么转到opencore？
黑果小兵的这篇文章不是很懂 https://blog.daliansky.net/From-Clover-To-OpenCore.html

我的配置跟你有些区别，蓝牙也是有问题
```
主板：ASRock Deskmini Intel H310 
cpu：i7 9700
无线网卡：DW1820
```

**Comment by huangyanan** [comment]
你好，可以基于我的配置调整序列号进行替换。
蓝牙部分kext我没有上传git，需要等工作日再进行共享。

**Comment by huangyanan** [comment]
[Hackintosh-EFI-for-deskmini-310-dw1820.zip](https://github.com/huangyanan/Hackintosh-EFI-for-deskmini-310-dw1820/files/7623053/Hackintosh-EFI-for-deskmini-310-dw1820.zip)
![image](https://user-images.githubusercontent.com/4048832/143988243-006040ab-f229-414c-88ca-fdca89224ddf.png)

**Comment by Jiyvn** [comment]
@huangyanan 好，非常感谢，我看看，很多设置都忘了，还需要研究下。
关于升级应该是可以opencore改完配置就用它引导升级？还是说我需要重新下载镜像覆盖安装？
